export const Strings = {
    AppName: 'KioskBoard',
    AppDescription: '키오스크 운영 보드',
    LightMode: 'Light Mode',
    DarkMode: 'Dark Mode',
    SwitchToLightMode: '라이트 모드로 전환',
    SwitchToDarkMode: '다크 모드로 전환',
    TodayLabel: '오늘',
    AddEvent: '행사 등록',
    Edit: '수정',
    Delete: '삭제',
    Save: '저장',
    Cancel: '취소',
    ConfirmDelete: '삭제하기',
    ViewLedger: '진행내역',
    ViewCalendar: '캘린더',
    ViewCompleted: '완료내역',
    SummaryAll: '전체 행사',
    SummaryScheduled: '예정',
    SummaryActive: '진행',
    SummaryCompleted: '완료',
    StatusUpcoming: '예정 + 진행',
    StatusScheduled: '예정',
    StatusActive: '진행',
    StatusCompleted: '완료',
    CompanyName: '회사명',
    EventName: '행사명',
    Content: '콘텐츠',
    ManagerName: '담당자',
    ManagerContact: '담당자 연락처',
    EventSchedule: '행사 일정',
    KioskCountUnit: '대',
    AssignedKiosks: '운용 키오스크',
    Selected: '선택',
    NoManagedKiosksForSelection: '설정에서 운용 키오스크를 먼저 등록해 주세요.',
    KioskUnavailablePrefix: '선택할 수 없습니다.',
    KioskUnavailableBecause: '행사 일정과 겹칩니다.',
    ContractCompleted: '계약 완료',
    DepositPaid: '선금 납부',
    BalancePaid: '잔금 납부',
    DeliveryCompleted: '납품 완료',
    InstallationDateTime: '설치 일시',
    RecoveryDateTime: '회수 일시',
    Notes: '메모',
    Status: '상태',
    Management: '관리',
    Paid: '완료',
    Unpaid: '미완료',
    EmptyLedgerTitle: '등록된 행사가 없습니다.',
    EmptyLedgerDescription: '행사를 등록하면 운영 현황을 바로 확인할 수 있습니다.',
    EmptyProgressTitle: '예정되거나 진행 중인 행사가 없습니다.',
    EmptyProgressDescription: '새 행사를 등록하면 진행내역에 표시됩니다.',
    EmptyFilterTitle: '조건에 맞는 행사가 없습니다.',
    EmptyFilterDescription: '다른 상태 필터를 선택해 보세요.',
    ProgressLedgerDescription: '예정 및 진행 중인 행사만 표시합니다.',
    EmptyCompletedTitle: '완료된 행사가 없습니다.',
    EmptyCompletedDescription: '종료일이 지난 행사가 여기에 자동으로 표시됩니다.',
    EmptyCalendarDescription: '등록된 일정이 없습니다.',
    PreviousMonth: '이전 달',
    NextMonth: '다음 달',
    CalendarToday: '이번 달',
    PickerClear: '지우기',
    PickerToday: '오늘',
    PickerApply: '적용',
    PickerHour: '시',
    PickerMinute: '분',
    Weekdays: ['일', '월', '화', '수', '목', '금', '토'],
    NewEventTitle: '새 행사 등록',
    EditEventTitle: '행사 정보 수정',
    EventDetailsTitle: '행사 정보',
    AssignedKiosksEmpty: '배정된 키오스크가 없습니다.',
    EventEditorDescription: '일정과 운영 정보를 입력하면 상태가 날짜에 따라 자동 계산됩니다.',
    EventStartDate: '행사 시작일',
    EventEndDate: '행사 종료일',
    MonthDayPlaceholder: '월 / 일',
    InstallationDateTimePlaceholder: '년 / 월 / 일 · 시간 / 분',
    RequiredFieldsError: '필수 항목을 모두 입력해 주세요.',
    InvalidDateRangeError: '행사 종료일은 시작일보다 빠를 수 없습니다.',
    InvalidRecoveryDateTimeError: '회수 일시는 행사 종료일보다 빠를 수 없습니다.',
    Settings: '설정',
    SignIn: '로그인',
    SignOut: '로그아웃',
    Email: '이메일',
    Password: '비밀번호',
    ShowPassword: '비밀번호 보기',
    HidePassword: '비밀번호 숨기기',
    SignInTitle: '로그인',
    SignInDescription: '초대받은 사내 계정으로 로그인해 주세요.',
    SignInRequiredError: '이메일과 비밀번호를 입력해 주세요.',
    SupabaseNotConfigured: 'Supabase 연결 설정이 없습니다.',
    BackupAndRestore: '백업 및 복구',
    BackupDescription: 'Saved 폴더의 JSON 백업을 선택해 서버 데이터를 복구합니다.',
    SelectBackupFile: 'JSON 선택',
    RestoreBackup: '복구하기',
    ConfirmRestoreBackup: '한 번 더 눌러 복구',
    BackupNotSelected: '선택된 백업 파일이 없습니다.',
    BackupRestoreWarning: '현재 서버 데이터가 선택한 백업 내용으로 교체됩니다.',
    BackupRestoreCompleted: '백업 데이터 복구가 완료되었습니다.',
    BackupRestoreFailed: '백업 데이터 복구에 실패했습니다.',
    KioskSettingsTitle: '운용 키오스크 설정',
    KioskSettingsDescription: '보유하고 있는 키오스크를 관리합니다.',
    ManagedKioskName: '키오스크 이름 또는 관리번호',
    ManagedKioskPlaceholder: '예: KIOSK-01',
    RegisterKiosk: '등록',
    LoadMore: '더보기',
    RegisteredKiosks: '등록된 키오스크',
    EmptyManagedKiosks: '등록된 키오스크가 없습니다.',
    DuplicateManagedKioskError: '이미 등록된 키오스크 이름입니다.',
    ManagedKioskRequiredError: '키오스크 이름 또는 관리번호를 입력해 주세요.',
    DeleteDialogTitle: '행사를 삭제할까요?',
    DeleteDialogDescription: '삭제한 행사 정보는 복구할 수 없습니다.',
    StorageError: '정보를 로컬 저장소에 저장하지 못했습니다.',
    SharedStorageError: '공유 저장소와 동기화하지 못했습니다. 인터넷 연결을 확인한 뒤 다시 시도해 주세요.',
    Loading: '행사 정보를 불러오는 중입니다.',
    CloseDialog: '창 닫기',
    Optional: '선택',
} as const;
